//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaExpense
    {
        public DaExpense()
        {
            this.DaExpenseAuditLogs = new HashSet<DaExpenseAuditLog>();
        }
    
        public int IntID { get; set; }
        public int IntContractGoodsID { get; set; }
        public decimal NumCount { get; set; }
        public decimal MonPrice { get; set; }
        public decimal MonSum { get; set; }
        public int IntStatus { get; set; }
        public string VcRemark { get; set; }
        public System.DateTime DtCreate { get; set; }
        public long IntEmpNum { get; set; }
        public int IntGoodsID { get; set; }
    
        public virtual DaContractGood DaContractGood { get; set; }
        public virtual DaGoods DaGood { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual ZdExpenseStatu ZdExpenseStatu { get; set; }
        public virtual ICollection<DaExpenseAuditLog> DaExpenseAuditLogs { get; set; }
    }
}
