//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaGoods
    {
        public DaGoods()
        {
            this.DaGoodsSuppliers = new HashSet<DaGoodsSupplier>();
            this.DaContractGoods = new HashSet<DaContractGood>();
            this.DaInvoices = new HashSet<DaInvoice>();
            this.DaStockIns = new HashSet<DaStockIn>();
            this.DaExpenses = new HashSet<DaExpense>();
        }
    
        public int IntID { get; set; }
        public string VcNum { get; set; }
        public string VcName { get; set; }
        public int IntUnit { get; set; }
        public string VcNorms { get; set; }
        public int IntTypeID { get; set; }
        public string VcRemark { get; set; }
        public System.DateTime DtCreate { get; set; }
        public long IntEmpNum { get; set; }
        public Nullable<decimal> MonPrice { get; set; }
        public Nullable<int> IntStatus { get; set; }
    
        public virtual T_Users T_Users { get; set; }
        public virtual DaGoodsType DaGoodsType { get; set; }
        public virtual ZdGoodsUnit ZdGoodsUnit { get; set; }
        public virtual ICollection<DaGoodsSupplier> DaGoodsSuppliers { get; set; }
        public virtual ICollection<DaContractGood> DaContractGoods { get; set; }
        public virtual ICollection<DaInvoice> DaInvoices { get; set; }
        public virtual ICollection<DaStockIn> DaStockIns { get; set; }
        public virtual ICollection<DaExpense> DaExpenses { get; set; }
        public virtual ZdGoodsStatu ZdGoodsStatu { get; set; }
    }
}
