//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaPurchaseContract
    {
        public DaPurchaseContract()
        {
            this.DaContractGoods = new HashSet<DaContractGood>();
            this.DaLoans = new HashSet<DaLoan>();
            this.DaPurchaseContractAuditLogs = new HashSet<DaPurchaseContractAuditLog>();
        }
    
        public int IntID { get; set; }
        public string VcNum { get; set; }
        public string VcTel { get; set; }
        public string VcFax { get; set; }
        public string VcMobile { get; set; }
        public int IntType { get; set; }
        public string VcCabinet { get; set; }
        public string VcFolder { get; set; }
        public int IntStatus { get; set; }
        public string VcRemark { get; set; }
        public System.DateTime DtCreate { get; set; }
        public long IntEmpNum { get; set; }
        public string VcLinkMan { get; set; }
        public int IntSupplierID { get; set; }
        public string VcApplicant { get; set; }
        public string VcApplicantDep { get; set; }
        public decimal MonSum { get; set; }
        public int IntCompanyID { get; set; }
    
        public virtual T_Users T_Users { get; set; }
        public virtual ZdContractStatu ZdContractStatu { get; set; }
        public virtual ICollection<DaContractGood> DaContractGoods { get; set; }
        public virtual DaSupplier DaSupplier { get; set; }
        public virtual DaCompany DaCompany { get; set; }
        public virtual ZdPurchaseContractType ZdPurchaseContractType { get; set; }
        public virtual ICollection<DaLoan> DaLoans { get; set; }
        public virtual ICollection<DaPurchaseContractAuditLog> DaPurchaseContractAuditLogs { get; set; }
    }
}
