//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaSupplier
    {
        public DaSupplier()
        {
            this.IntStatus = 0;
            this.DaGoodsSuppliers = new HashSet<DaGoodsSupplier>();
            this.DaSupplierContacts = new HashSet<DaSupplierContact>();
            this.DaPurchaseContracts = new HashSet<DaPurchaseContract>();
        }
    
        public int IntID { get; set; }
        public string VcNum { get; set; }
        public string VcName { get; set; }
        public string VcRegCapital { get; set; }
        public string VcLegalRep { get; set; }
        public string VcTaxID { get; set; }
        public string VcOpeningBank { get; set; }
        public string VcBankAccount { get; set; }
        public string VcAddress { get; set; }
        public string VcWebsite { get; set; }
        public string VcTel { get; set; }
        public string VcFax { get; set; }
        public string VcPostCode { get; set; }
        public int IntStatus { get; set; }
        public string VcRemark { get; set; }
        public System.DateTime DtCreate { get; set; }
        public long IntEmpNum { get; set; }
    
        public virtual T_Users T_Users { get; set; }
        public virtual ICollection<DaGoodsSupplier> DaGoodsSuppliers { get; set; }
        public virtual ICollection<DaSupplierContact> DaSupplierContacts { get; set; }
        public virtual ICollection<DaPurchaseContract> DaPurchaseContracts { get; set; }
    }
}
