//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYDBEntities2 : DbContext
    {
        public MYDBEntities2()
            : base(Common.CommonClass.EFConnStr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DaGoods> DaGoods1 { get; set; }
        public DbSet<DaGoodsType> DaGoodsTypes { get; set; }
        public DbSet<DaInvoice> DaInvoices { get; set; }
        public DbSet<DaPurchaseContract> DaPurchaseContracts { get; set; }
        public DbSet<DaSupplier> DaSuppliers { get; set; }
        public DbSet<DaSupplierContact> DaSupplierContacts { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
        public DbSet<ZdContractStatu> ZdContractStatus { get; set; }
        public DbSet<ZdGoodsUnit> ZdGoodsUnits { get; set; }
        public DbSet<ZdInvoiceType> ZdInvoiceTypes { get; set; }
        public DbSet<DaGoodsSupplier> DaGoodsSuppliers { get; set; }
        public DbSet<DaStockIn> DaStockIns { get; set; }
        public DbSet<DaContractGood> DaContractGoods { get; set; }
        public DbSet<DaCompany> DaCompanies { get; set; }
        public DbSet<ZdStockInStatu> ZdStockInStatus { get; set; }
        public DbSet<ZdPurchaseContractType> ZdPurchaseContractTypes { get; set; }
        public DbSet<ZdInvoiceStatu> ZdInvoiceStatus { get; set; }
        public DbSet<DaExpense> DaExpenses { get; set; }
        public DbSet<ZdExpenseStatu> ZdExpenseStatus { get; set; }
        public DbSet<DaLoan> DaLoans { get; set; }
        public DbSet<ZdLoanStatu> ZdLoanStatus { get; set; }
        public DbSet<DaExpenseAuditLog> DaExpenseAuditLogs { get; set; }
        public DbSet<DaPurchaseContractAuditLog> DaPurchaseContractAuditLogs { get; set; }
        public DbSet<ZdGoodsStatu> ZdGoodsStatus { get; set; }
        public DbSet<PTDepartment> PTDepartments { get; set; }
        public DbSet<PTMenu> PTMenus { get; set; }
        public DbSet<PTOperation> PTOperations { get; set; }
        public DbSet<PTRole> PTRoles { get; set; }
        public DbSet<PTzqx> PTzqxes { get; set; }
    }
}
