//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 销售管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTMenu
    {
        public string MKBH { get; set; }
        public string MKMC { get; set; }
        public Nullable<int> MKJB { get; set; }
        public string MKFCD { get; set; }
        public string MKTP { get; set; }
        public string MKWJM { get; set; }
        public string MKHSM { get; set; }
        public string BBH { get; set; }
        public Nullable<int> CardType { get; set; }
        public bool FastStart { get; set; }
    }
}
